In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
import sklearn
import shap
import matplotlib.pyplot as plt

print("pandas:", pd.__version__)
print("xgboost:", xgb.__version__)
print("sklearn:", sklearn.__version__)
print("shap:", shap.__version__)
print("All libraries working!")

pandas: 3.0.2
xgboost: 3.2.0
sklearn: 1.8.0
shap: 0.51.0
All libraries working!

In [2]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.0-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
Downloading lxml-6.1.0-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.8 MB/s eta 0:00:02
   ------- -------------------------------- 0.8/4.0 MB 1.0 MB/s eta 0:00:04
   ---------- ----------------------------- 1.0/4.0 MB 1.2 MB/s eta 0:00:03
   ------------- -------------------------- 1.3/4.0 MB 1.2 MB/s eta 0:00:03
   --------------- ------------------------ 1.6/4.0 MB 1.3 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.2 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.2 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.2 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.2 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.2 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 1.2 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 1.2 MB/s eta 0:00:01
   ---------------------------------- ----- 3.4/4.0 MB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.2 MB/s  0:00:03
Installing collected packages: lxml
Successfully installed lxml-6.1.0

In [5]:
import pandas as pd
# Load the file you just saved
df = pd.read_csv('../data/raw/odi_most_runs_2026.csv')
# Show the first few rows
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DJ Mitchell (NZ),2026-2026,3,3,1,352,137,176,319,110.34,2,1,0,31,8
1,Tanzid Hasan (BAN),2026-2026,5,5,1,253,107,63.25,220,115.00,1,2,0,23,16
2,JE Root (ENG),2026-2026,3,3,1,247,111*,123.5,288,85.76,1,2,0,19,1
3,V Kohli (IND),2026-2026,3,3,0,240,124,80,228,105.26,1,1,0,20,4
4,Hammad Mirza (OMA),2026-2026,3,3,1,201,112*,100.5,239,84.10,1,1,0,20,1

In [6]:

import pandas as pd
# Load the file you just saved
df = pd.read_csv('../data/raw/most_wickets_odi_2026.csv')
# Show the first few rows
df.head()

,Player,Span,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,4,5
0,Nahid Rana (BAN),2026-2026,5,5,282,47.0,1,242,14,24-May,17.28,5.14,20.14,0,2
1,Hassnain Shah (OMA),2026-2026,3,3,132,22.0,0,122,9,26-Apr,13.55,5.54,14.66,1,0
2,Taskin Ahmed (BAN),2026-2026,5,5,268,44.4,2,233,9,Apr-49,25.88,5.21,29.77,1,0
3,J Jarvis (SCOT),2026-2026,3,3,130,21.4,0,96,7,Mar-35,13.71,4.43,18.57,0,0
4,AU Rashid (ENG),2026-2026,3,3,180,30.0,0,139,7,Mar-44,19.85,4.63,25.71,0,0